language: go

variables:
  GOPROXY: "off"

go:
# must be quoted in order to work correctly
- "1.15.x"
- master

before_install:
- go get -t -v ./...

script:
- go test -mod vendor -race -coverprofile=coverage.txt -covermode=atomic ./...
- make clean
- make build
# validate for correct generation
- make generate 

after_success:
# Report test cover status
- bash <(curl -s https://codecov.io/bash) 